name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.14.0

      - name: Install dependencies
        run: npm ci

      - name: Run Biome Lint
        run: npm run lint

      - name: Run TypeScript Type Check
        run: npm run type-check

      - name: Build Project
        run: npm run build
